stage("Git: Code update and push to GitHub") {
    steps {
        script {
            withCredentials([usernamePassword(credentialsId: 'Github-cred', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASS')]) {
                sh """
                    echo "Checking repository status..."
                    git status

                    echo "Adding changes to git..."
                    git add .

                    echo "Committing changes..."
                    git commit -m "Updated environment variables" || echo "No changes to commit"

                    echo "Setting git identity..."
                    git config user.email "jenkins-bot@example.com"
                    git config user.name "jenkins-bot"

                    echo "Pushing changes to GitHub..."
                    git push https://${GIT_USER}:${GIT_PASS}@github.com/sahukalu/Wanderlust-Mega-Project.git main
                """
            }
        }
    }
}
